
server:
    port: 8090    

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: task-service
        uri: lb://task-service
        predicates:
        - Path=/tasks/**
 
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka