
eureka:
    instance:
        hostname: localhost
logging:
    file:
        name: taskmodule.log
        path: .
server:
    port: 9090
spring:
    application:
        name: task-service
    datasource:
        driver-class-name: org.postgresql.Driver
        password: root
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create
        show-sql: true